{
 "title": "Churn Risk Service Dashboard",
 "tags": [
  "task1",
  "churn",
  "devops"
 ],
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "Request Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    { "expr": "rate(churn_requests_total[1m])", "legendFormat": "requests/sec" }
   ]
  },
  {
   "title": "Predictions by Risk",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "sum by (risk) (churn_prediction_total)",
     "legendFormat": "{{risk}}"
    }
   ]
  },
  {
   "title": "Average Latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "churn_request_duration_seconds_sum / clamp_min(churn_request_duration_seconds_count, 1)",
     "legendFormat": "avg latency"
    }
   ]
  }
 ]
}